files:
  include: "src/**/**/**/*.s+(a|c)ss"
  ignore:
    - node_modules/**
syntax:
    include:
      - scss
      - sass
resolvers:
  indentation: 1
  property-sort-order: 1
  attribute-quotes: 1
  border-zero: 1
  no-color-keywords: 1
  no-css-comments: 0
  no-important: 1
  no-trailing-zero: 1
  space-after-bang: 0
  space-before-bang: 1
  space-after-colon: 1
  space-before-colon: 0
  space-between-parens: 0
  hex-length: 1
  empty-line-between-blocks: 1
  url-quotes: 1
  shorthand-values:
  zero-unit: 1
  hex-notation: 1
  final-newline: 0
options:
  optOut: true