on: pull_request
name: Pull Request Checks
jobs:
  test:
    name: Webapp Pull Request Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Package & Release
        env:
          GITHUB_AUTHOR_NAME: ${{ secrets.GITHUB_AUTHOR_NAME }}
          GITHUB_AUTHOR_EMAIL: ${{ secrets.GITHUB_AUTHOR_EMAIL }}
          GITHUB_COMMITTER_NAME: ${{ secrets.GITHUB_COMMITTER_NAME }}
          GITHUB_COMMITTER_EMAIL: ${{ secrets.GITHUB_COMMITTER_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SEMANTIC_RELEASE_PACKAGE: ${{ secrets.SEMANTIC_RELEASE_PACKAGE }}
          JIRA_AUTH: ${{ secrets.JIRA_AUTH }}
        run: npx semantic-release
      - name: Prepare Deploy Variables
        run: |
          echo "name=WEBAPP_VERSION::$(cat .semvernext)" >> $GITHUB_ENV
          echo "name=WEBAPP_PACKAGE::zignaly-webapp2-$(cat .semvernext).tar.gz" >> $GITHUB_ENV
          echo "$WEBAPP_PACKAGE"
      # - name: Dependencies
      #   run: npm ci
      # - name: Check Style Lint
      #   run: npm run stylelint
      # - name: Check JS Lint
      #   run: npm run jslint
      # - name: Check Types
      #   run: npm run tscheck
      # - name: Test
      #   env:
      #     GATSBY_API_KEY: ${{ secrets.GATSBY_API_KEY }}
      #     GATSBY_API_TEST_USER: ${{ secrets.GATSBY_API_TEST_USER }}
      #     GATSBY_API_TEST_PASS: ${{ secrets.GATSBY_API_TEST_PASS }}
      #   run: npm test
